### PR TITLE
Add matrix gem to runtime dependency, required for ruby 3.1+

### PR DESCRIPTION
**Pull request by mathieujobin**

### CODE REVIEW

**Review by phillbaker — COMMENTED** [review]
Hi, thanks for the contribution. Similar to https://github.com/rails/rails/pull/42366/, can we wrap this in a `if RUBY_VERSION >= "3.1"` block?

Ref: 
* https://github.com/ruby/ruby/pull/4530
* https://stdgems.org/

**Comment by phillbaker** [comment]
Cherry-picked here: f90b0ac. Thanks for your contribution.

**Comment by mathieujobin** [comment]
Thanks, will you make a release?

**Comment by phillbaker** [comment]
Yes, it's been published.

**Comment by High5Apps** [comment]
Hi Phillip and Mathieu,
Thanks to both of you for your work on rubystats. 

I recently tried to install 0.4.0 and ran into the following issue when starting up my rails project immediately after the `bundle install`.
```
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- matrix (LoadError)
```

As such, I think this pull-request may have a bug. I found a thread that may be relevant in the [rubocop/ruby-style-guide](https://github.com/rubocop/ruby-style-guide) repo: [Do not use RUBY_VERSION in gemspec](https://github.com/rubocop/ruby-style-guide/issues/763) (The relevant parts are quoted at the end of my comment.)

I was able to fix the error by explicitly adding matrix to my Gemfile and running `bundle install` again. As a result, I think that removing the `if RUBY_VERSION >= "3.1"` will likely fix the issue for others on 3.1+. And for users <3.1, I don't think it should be a problem either- even though ruby <3.1 had matrix pre-installed, it's not like it would get installed twice, right? Admittedly I'm not an expert on gems/bundler, so please correct me if that thinking is incorrect.

If you think that sounds reasonable, I can create a PR to remove the `if`.

Thanks again for your work on rubystats,
Julian

- - -

> Gemspec should not contain RUBY_VERSION as a condition to switch dependencies.
For example:

>
```rb
Gem::Specification.new do |s|
  if RUBY_VERSION >= '2.5'
    s.add_runtime_dependency 'gem_a'
  else
    s.add_runtime_dependency 'gem_b'
  end
end
```
> It has unexpected behavior. The RUBY_VERSION is determined by `rake release`.
If I use Ruby 2.5 to execute `rake release`, the gem always has gem_a as a dependency even if a user installs the gem with Ruby 2.4 or older.
> We have several ways to fix the problem.
> - Remove the dependencies and use `post_install_message` to notice the gems.
> - Add both gems to the dependency.
> - If the dependencies are for development, move them to Gemfile.

**Comment by mathieujobin** [comment]
The point is ! Ruby used to ship with `matrix` gem built-in.
Ruby 3.2 no more; and this gem requires it. Thus it should be specified as a dependency.

**Comment by High5Apps** [comment]
I agree that the `matrix` gem now needs to be specified as a dependency. And I think the PR above was the right way to do it:
```rb
s.add_runtime_dependency("matrix")
```

However, as a result of the discussion in the thread above, this code is what was actually merged in [f90b0ac](https://github.com/phillbaker/rubystats/commit/f90b0ac):
```rb
if RUBY_VERSION >= "3.1"
  # matrix was removed from default gems in Ruby 3.1, see
  # https://github.com/ruby/ruby/pull/4530 and https://stdgems.org/
  s.add_runtime_dependency("matrix")
end
```

To fix my issue mentioned above, I would like to make the gemspec look like the first block instead of the second block.

**Comment by phillbaker** [comment]
Hi, thanks for the explanation. A PR for that update would be great!

**Pull request closed without merging**
