### PR TITLE
fix to prevent integer calculations when distributions are initialize…

### PR DESCRIPTION
**Pull request by konimarti**
…d with integers but float precision is required for accurate calculations

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks! Can you add tests to make sure this behavior is caught going
forward?

**Comment by konimarti** [comment]
Happy to contribute. Good idea with the tests. I assume a test along the lines of NormalDistribution(10,2).pdf(11) == NormalDistribution(10.0,2.0).pdf(11.0) should work.

**Comment by konimarti** [comment]
Added tests for the beta, normal, and exponential distributions. Fisher's exact test and binomial distribution are based on counts.

**Comment by phillbaker** [comment]
Thanks!

**Pull request merged**
